[package]
name = "qoj-interface"
version = "0.1.0"
authors = ["quickshell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "0.8"
mime = "0.3"
iso639-1 = "0.3"
chrono = "0.4"